### ISSUE TITLE
[feature request] Desktop Safari

### ISSUE THREAD

**Issue by eirnym** [cowbell/sharedrop#58]
Why do you not support Safari? Just forgot to include to the list? Which exactly instructions/functions/technologies you so badly need to support browser?

**Comment by eirnym** [comment]
BTW, Mega.nz works fine with Safari even they heavy cryptography

**Comment by szimek** [comment]
Please see this issue: https://github.com/cowbell/sharedrop/issues/57

In short: Safari 10 and earlier don't support WebRTC data channels and thus don't allow to have real peer-to-peer communication. AFAIK all existing solutions use intermediate server and e.g. websockets, which I want to avoid. It looks like Safari 11 might support everything that's required to make it work, but because I haven't really touched this code in a long time, it might take a while for me to release a new version with Safari (and Edge) support.

**Comment by eirnym** [comment]
These browsers are NOT the same and have a lot of differences

**Comment by szimek** [comment]
Which browsers?

**Comment by eirnym** [comment]
Safari for iPad/iPhone and Desktop Safari

**Comment by eirnym** [comment]
And you haven't answered about technologies you so badly need in JS.

Safari: 10.1.2
Safari Technology Preview: 11.1
Nightly WebKit

**Comment by szimek** [comment]
Sure I did: WebRTC data channels.
