### ISSUE TITLE
Feature request: Transfer multiple files at once

### ISSUE THREAD

**Issue by iBobik** [cowbell/sharedrop#64]
Multiple files are not accepted by select dialog neither drag&drop.

**Comment by txjohn69** [comment]
Multiple files would be nice...however you can just zip up the files and send the single archive

**Comment by benwinding** [comment]
Apple's Airdrop allow's this and it's extremely useful.

One of the most common use-case's is to transfer multiple photos from a phone to a computer... 

Is there any plans to develop this feature?

**Comment by valoricDe** [comment]
Who want's to start with this?
I guess we would need to update:
https://github.com/cowbell/sharedrop/blob/master/app/components/file-field.js
https://github.com/cowbell/sharedrop/blob/master/app/templates/components/peer-widget.hbs
https://github.com/cowbell/sharedrop/blob/master/app/controllers/index.js

I'm unsure if we need multiple file-field's or the file-field would need to pass the file array to the uploadFile method

**Comment by GO3LIN** [comment]
I am really interested to help on this, will have some time this weekend 👍

**Comment by valoricDe** [comment]
Hmm, zip is a good idea but that makes it much more complex I guess. I imagine a smartphone where a user selects 500 images which would need to be packaged up to a zip file. Which either doesn't work at all due to ram limitations or would require a progress bar.
But let's create a protoype with https://www.npmjs.com/package/jszip
maybe we can also use something like this https://www.npmjs.com/package/zip-stream to stream the data right away so that the data can already transfered.

**Comment by valoricDe** [comment]
Actually is seems to be possible to use https://stuk.github.io/jszip/documentation/api_jszip/generate_internal_stream.html, https://stuk.github.io/jszip/documentation/api_zipobject/internal_stream.html to generate a zip stream.

**Comment by szimek** [comment]
@valoricDe Thanks again for implementing this feature! It is deployed to production 🎉
